config = {'train_data_path':['/data_set_medical/lyshi/LUNA16/subset9/',
                             '/data_set_medical/lyshi/LUNA16/subset1/',
                             '/data_set_medical/lyshi/LUNA16/subset2/',
                             '/data_set_medical/lyshi/LUNA16/subset3/',
                             '/data_set_medical/lyshi/LUNA16/subset4/',
                             '/data_set_medical/lyshi/LUNA16/subset5/',
                             '/data_set_medical/lyshi/LUNA16/subset6/',
                             '/data_set_medical/lyshi/LUNA16/subset7/',
                             '/data_set_medical/lyshi/LUNA16/subset8/'],
          'val_data_path':['/data_set_medical/lyshi/LUNA16/subset0/'], 
          'test_data_path':['/data_set_medical/lyshi/LUNA16/subset0/'], 
          
          'train_preprocess_result_path':'/data_set_medical/lyshi/LUNA16/processed/', # contains numpy for the data and label, which is generated by prepare.py
          'val_preprocess_result_path':'/data_set_medical/lyshi/LUNA16/processed/',  # make sure copy all the numpy into one folder after prepare.py
          'test_preprocess_result_path':'/data_set_medical/lyshi/LUNA16/processed/',
          
          'train_annos_path':'/data_set_medical/lyshi/LUNA16/annotations.csv',
          'val_annos_path':'/data_set_medical/lyshi/LUNA16/annotations.csv',
          'test_annos_path':'/data_set_medical/lyshi/LUNA16/annotations.csv',

          'black_list':[],
          
          'preprocessing_backend':'python',

          'luna_segment':'/data_set_medical/lyshi/LUNA16/seg-lungs-LUNA16/', # download from https://luna16.grand-challenge.org/data/
          'preprocess_result_path':'/data_set_medical/lyshi/LUNA16/processed/',
          'luna_data':'/data_set_medical/lyshi/LUNA16/',
          'luna_label':'/data_set_medical/lyshi/LUNA16/annotations.csv'
         } 
