config = {'train_data_path':[#'/home/hugoycj/Database/Dataset/LUNA16/subset9/',
                             #'/home/hugoycj/Database/Dataset/LUNA16/subset1/',
                             #'/home/hugoycj/Database/Dataset/LUNA16/subset2/',
                             #'/home/hugoycj/Database/Dataset/LUNA16/subset3/',
                             #'/home/hugoycj/Database/Dataset/LUNA16/subset4/',
                             #'/home/hugoycj/Database/Dataset/LUNA16/subset5/',
                             #'/home/hugoycj/Database/Dataset/LUNA16/subset6/',
                             #'/home/hugoycj/Database/Dataset/LUNA16/subset7/',
                             '/home/hugoycj/Database/Dataset/LUNA16/subset8/'],
          'val_data_path':['/home/hugoycj/Database/Dataset/LUNA16/subset0/'], 
          'test_data_path':['/home/hugoycj/Database/Dataset/LUNA16/subset0/'], 
          
          'train_preprocess_result_path':'/home/hugoycj/Database/Dataset/LUNA16/prepare/', # contains numpy for the data and label, which is generated by prepare.py
          'val_preprocess_result_path':'/home/hugoycj/Database/Dataset/LUNA16/prepare/',  # make sure copy all the numpy into one folder after prepare.py
          'test_preprocess_result_path':'/home/hugoycj/Database/Dataset/LUNA16/prepare/',
          
          'train_annos_path':'/home/hugoycj/Database/Dataset/LUNA16/CSVFILES/annotations.csv',
          'val_annos_path':'/home/hugoycj/Database/Dataset/LUNA16/CSVFILES/annotations.csv',
          'test_annos_path':'/home/hugoycj/Database/Dataset/LUNA16/CSVFILES/annotations.csv',

          'black_list':[],
          
          'preprocessing_backend':'python',

          'luna_segment':'/home/hugoycj/Database/Dataset/LUNA16/seg-lungs-LUNA16/', # download from https://luna16.grand-challenge.org/data/
          'preprocess_result_path':'/home/hugoycj/Database/Dataset/LUNA16/prepare/',
          'luna_data':'/home/hugoycj/Database/Dataset/LUNA16/',
          'luna_label':'/home/hugoycj/Database/Dataset/LUNA16/CSVFILES/annotations.csv'
         } 
